# ntopng Enterprise Interface Configuration Specification
# Target Interface: Local Ethernet Interface
-i=eth0

# HTTP Management Web Server Port Routing
-w=3000

# Analytical Data Isolation Criteria
# Disables login authentication requirements for internal local LAN subnet profiling
--skip-signin=1

# Storage optimization parameters: local interface packet dump restrictions
--packet-filter="not multicast and not broadcast"
